<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>ColorModelConverter.App</RootNamespace>
    <AssemblyName>ColorModelConverter</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ColorModelConverter.Core\ColorModelConverter.Core.csproj" />
  </ItemGroup>

</Project>
