<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>ImageMetadataViewer.Engine</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ImageMetadataViewer.Infrastructure\ImageMetadataViewer.Infrastructure.csproj" />
  </ItemGroup>

</Project>
